# Generated by Django 2.2 on 2020-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
