# Generated by Django 2.2 on 2020-04-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_app', '0003_planet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.TextField(default=''),
        ),
    ]
